apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk-test
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/<your-azure-sub-id>/resourceGroups/<your-node-resourcegroup-name>/providers/Microsoft.Compute/disks/myAKSDisk
    volumeAttributes:
      fsType: ext4
